

stop_wssaprogram_words <- c("natalie","crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", "proceedings", "ncwss",
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "gerald", "dill", "czapar",
                            "dinicola", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", "proceedings", "ncwss",
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", "proceedings", "ncwss",
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle",
                            "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", "proceedings", "ncwss",
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle",
                            "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", "morris",
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", 
                            "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", 
                            "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle",
                            "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", 
                            "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "wetherford", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", "wetherford",
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "lincoln", "crop", "university", "universidad", "universidade", "location",    
                            "agriscience", "usda", "monarchy", "north", "march", "moderator",
                            "extension", "college", "tech", "time", "student", "contest",
                            "break", "station", "basf", "division", "ars", "fort", "guelph",
                            "presenter", "maui", "monday", "tuesday", "wednesday", "thursday",
                            "oral", "poster", "united", "western", "speaker", "science", "lleida",
                            "dakota", "agriculture", "service", "laramie", "forest", "piracicaba",
                            "purdue", "agrilife", "center", "syngenta", "morning", "afternoon",
                            "agri", "ventenata", "center", "east", "food", "tifton", "adelaide",
                            "pullman", "resources", "affiliation", "saskatoon", "saskatchewan",   
                            "moscow", "park", "suite", "west", "corteva", "bayer", "frankfurt",
                            "cropscience", "beltsville", "south", "northeast", "northern",  
                            "northwest", "platte", "central", "cooperative", "cornell", "phd",
                            "program", "maui", "clemson", "stoneville", "baton", "rouge",
                            "ridgetown", "buenos", "ithaca", "são", "cordoba", "usa", "carbondale",
                            "sur", "river", "system", "johnson", "athens", "city", "usp", "paulo",
                            "pelotas", "aires", "winfield", "llc", "são", "kingdom", "pnw",
                            "lexington", "eastern", "mornings", "brookings", "southern", "federal",
                            "scottsbluff", "ontario", "manitoba", "thorntown", "lexiton",
                            "newport", "macomb", "penn", "institute", "islands", "summit",
                            "shoreview", "ndsu", "collins", "smithville", "europe", "antonio",
                            "winnipeg", "saint", "fmc", "brookston", "southeastern", "protection",
                            "agrosciences", "monsanto", "louis", "campus", "bangkok", "collins",
                            "council", "corporation", "rio", "grande", "harrow", "aac", "aafc",
                            "beach", "aberdeen", "brunswick", "napa", "rutgers", "mills", "falls",
                            "wakefield", "wayne", 
                            "valent","society", "starkville", "department", "sheridan", "viçosa",
                            "lonoke", "osmond", "las", "cruces", "makawao", "painter", "lethbridge",
                            "daejeon", "moghu", "bridgestone", "princeton", "lafayette", "hastings",
                            "symposium", "volcano", "colfax", "greeley", "boulder", "seffner", "des",
                            "moines", "amvac", "lees", "crawley", "kyoto", "manoa", "bonham", "posters",
                            "langley", "waipahu", "salinas", "pontotoc", "richelieu", "galena",
                            "beebe", "calgary", "bogor", "jean", "hampshire", "trinity", "triangle",
                            "york", "monticello", "bogotá", "calgary", "albion", "alegre", "arabia",
                            "saudi", "balm", "bay", "brooks", "bury", "committee", "csic", "daniel",
                            "dow", "edmonton", "edmunds", "edwardsville", "eloy", "esalq","goldsboro",
                            "hettinger", "iaa", "korea", "lacombe", "jaboticabal", "keenesburg",
                            "marina", "mcminnville", "maringa", "marrone", "morrisville", "monterey",
                            "nufarm", "oak", "ncsu", "nacional", "ottawa", "pendleton", "pat",
                            "porto", "plc", "stephenville", "steckel", "tokyo", "universitat", "vero",
                            "univ", "wageningen", "wooster", "christi", "corpus", "company", "dryden",
                            "glenn", "nice", "nrcs", "oroville", "susanville", "amworth", "yuba",
                            "hays", "bracknell", "agcenter", "americas", "america", "immokalee", "papers",
                            "harpenden", "rothamsted", "wagga", "county", "hawaiian", "belgrade",
                            "national", "pacific", "adams", "bayer", "dupont", "dow", "johnston",
                            "layfette", "queensland", "gatton", "rochelle", "todd", "owen", "malcolm",
                            "medlin", "volmmer")



stop_wssaprogram_words <- as_tibble(stop_wssaprogram_words) %>% 
  distinct()


# first names
first <- corpora("humans/firstNames")
stopwords_first <- c(first$firstNames)
stopwords_first <- tolower(stopwords_first)


# cities and states
geography <- corpora("geography/us_cities")
cities <- geography$cities
stopwords_cities <- c(cities$city) # stop cities words 
stopwords_cities <- tolower(stopwords_cities)  # making small caps
stopwords_state <- c(cities$state) # stop state words 
stopwords_state <- tolower(stopwords_state) # making lowercase

#country
country <- corpora("geography/countries") # stop country words 
stopwords_countries <- c(country$countries) # stop countries words 
stopwords_countries <- tolower(stopwords_countries) # making lowercase

#capitals
capitals <- corpora("geography/us_state_capitals")
capitals <- c(capitals$capitals)  # stop US capital words 
stopwords_capitals <- c(capitals$capital) # stop us capitals words 
stopwords_capitals <- tolower(stopwords_capitals) # making lowercase

#english
Enlish <-corpora("words/stopwords/en")  
stopwords_en <- c(Enlish$stopWords) # stop english words 
stopwords_en <- tolower(stopwords_en) # making lowercase

