---
title: "tidy_ncwss"
author: "Maxwel Coura Oliveira"
date: "2/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = TRUE,
  warning = TRUE
  )
```

```{r}
library(tidyverse)
library(tidytext)
library(textreadr)
library(pdftools)
library(ggtext)
```


```{r}
pdfs <- paste("docs", "/", list.files("docs", pattern = "*.pdf"), sep = "")
pdf_names <- list.files("docs", pattern = "*.pdf")  
pdfs_text <- map(pdfs, pdftools::pdf_text)
```

```{r}
pdf <- tibble(document = pdf_names, text = pdfs_text) %>% 
  mutate(year = 2001:2019)
```

```{r unnest-tokens}
pdf1 <- pdf %>% 
  unnest(text) %>% # pdfs_text is a list
  mutate(text = str_to_lower(text),
         text = str_replace(text, "2,4-d","twofourd")) %>% # need to replace it
  unnest_tokens(word, text, strip_numeric = TRUE)
```


```{r stopwords}
stopwords <- get_stopwords("en", source = c("smart")) %>% 
  bind_rows(get_stopwords("en", source = c("marimo"))) %>% 
  bind_rows(get_stopwords("en", source = c("nltk"))) %>% 
  bind_rows(get_stopwords("en", source = c("stopwords-iso"))) %>% 
  bind_rows(get_stopwords("en", source = c("snowball")))
```

```{r cleaning}
pdf2 <- pdf1 %>% 
  anti_join(stopwords, by = "word") %>% 
  anti_join(stop_wssaprogram_words, by = "word") %>% 
  mutate(word = str_replace(word, "twofourd", "2,4-d")) %>% 
  group_by(year) %>%
  mutate(line = row_number()) 
```



```{r}
pdf3 <- pdf2 %>% 
  count(year, word) %>% 
  arrange(year, -n) %>% 
  group_by(year) %>% 
  mutate(rank = row_number()) %>% 
  filter(rank <= 100)
```






```{r}
pdf4 <- pdf3 %>% 
  mutate(highlight = ifelse(word %in% c("amaranth", "palmer", "kochia", "horseweed", "grass", "nightshade", "waterhemp", "velvetleaf", "ragweed", "sunflower",
                                            "foxtail"), TRUE, FALSE),
       variable_col = if_else(highlight == TRUE, word, "NA"))
```



```{r}
#Set theme
library(extrafont)
#font_family <- 'Arial' 
background <- "#1D1D1D"
text_colour <- "white"
axis_colour <- "white"
plot_colour <- "black"
theme_style <- theme(#text = element_text(family = font_family),
                  rect = element_rect(fill = background),
                  plot.background = element_rect(fill = background, color = NA),
                  plot.title = element_markdown(family = "Arial Rounded MT Bold",
                                            face = 'bold', size = 50, colour = text_colour),
                  plot.subtitle = element_text(size = 30, colour = text_colour),
                  plot.caption = element_text(size = 20, colour = text_colour),
                  panel.background = element_rect(fill = background, color = NA),
                  panel.border = element_blank(),
                  panel.grid.major.y = element_blank(),
                  panel.grid.major.x = element_blank(),
                  panel.grid.minor.x = element_blank(),
                  plot.margin = unit(c(3, 0.5, 0.5, 0.5), "cm"), # top, left, bottom, right
                  axis.title.y = element_text(face = 'bold', size = 40, 
                                              colour = text_colour),
                  axis.title.x = element_blank(),
                  axis.text.x.bottom = element_text(size = 45, colour= axis_colour, 
                                                    vjust = 17),
                  axis.text.x.top = element_text(size = 45, colour= axis_colour, 
                                                    vjust = -14),
                  axis.text.y = element_text(size = 30, colour = text_colour),
                  axis.ticks = element_blank(),
                  axis.line = element_blank(),
                  legend.text = element_text(size = 20, colour= text_colour),
                  legend.title = element_text(size = 25, colour= text_colour),
                  legend.position="none") 


theme_set(theme_classic() + theme_style)

#Set colour palette
cols <- c("#FE5F55", "#4281A4", "#48A9A6", "#D4B483", "#E4DFDA", "#C1666B", "#39393A")
```



```{r}
pdf4 %>% 
  ggplot(aes(x = year, y = rank, group = word)) +
  geom_line(data = pdf4 %>% filter(variable_col == "NA"),
                                      color = "#39393A", size = 4) +
  geom_point(data = pdf4 %>% filter(variable_col == "NA"),
                                      color = "#39393A", size = 10) +
  geom_line(data = pdf4 %>% filter(variable_col != "NA"),
                                       aes(color = variable_col), size = 4) +
  geom_point(data = pdf4 %>% filter(variable_col != "NA"),
                                       aes(color = variable_col), size = 10) +
  scale_y_reverse(breaks = 100:1) +
  scale_x_continuous(breaks = seq(2001, 2019, 2), limits= c(2000, 2020), 
                     expand = c(.05, .05), sec.axis = dup_axis()) +
  geom_text(data = pdf4 %>% filter(year == "2001"),
            aes(label = word, x = 2000.8, color = variable_col),
            hjust = "right",
            fontface = "bold",
            size = 11) +
  geom_text(data = pdf4 %>%  filter(year == "2019"),
            aes(label = word, x = 2019.2, color = variable_col),
            hjust = "left",
            fontface = "bold",
            size = 11) +
  coord_cartesian(ylim = c(101,1)) +
   scale_color_manual(values = c("#F2D9F3", "#F2D9F3", "#00E5E5", "#DEB887", 
                                 "#FAC8C8", "#39393A", 
                                 "#FA9664", "#FF4040",    
                                 "#48DE7A", "#942DC7", "#F5F5DC", 
                                 "#FAFA00")) +
    labs(title = "NCWSS Meeting text analysis of title and abstracts from 2001 through 2019",
       subtitle = "Rank of the top 100 words of each NCWSS annual meeting proceeding with selected highlighted herbicides", 
       y= "Rank",
       caption = "Visualization: @maxwelco adapted from @JaredBraggins | Source: NCWSS")  +

#Export plot
ggsave("word_rank_herb.pdf", width = 40, height = 60, dpi=300, limitsize = FALSE)
```


